config/routes.rb
Rails.application.routes.draw do
  get 'about/index', to: 'about#index', as: 'about'
  get 'home/index'
  devise_for :users
  resources :links do
    member do
      get "visit_counter_chart"
      get "visit_detail"
    end
  end
  get "l/:slug" => "links#redirect_original_url", as: :redirect_original_url
  post "l/:slug" => "links#private_link_authentication", as: :private_link_authentication
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "home#index"
end

app/views/shared/_flash.html.erb
<%# Generate flash alert and notice messages with SweetAlert2 %>
<% if notice %>
  <script>
     Swal.fire({ 
       icon: 'success', 
       title: '<%= notice %>', 
       showConfirmButton: false, 
       timer: 1500 
     }) 
   </script> 
 <% end %> 
 <% if alert %> 
   <script> 
     Swal.fire({ 
       icon: 'error', 
       title: '<%= alert %>', 
       showConfirmButton: false, 
       timer: 1500 
     }) 
   </script> 
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
    Chqto &copy; 2023
</div>

app/views/shared/_header.html.erb
<nav class="navbar">
  <ul>
    <li><%= link_to 'Home', root_path, :class => 'navbar-link'  %></li>
    <li><%= link_to 'About', about_path, :class => 'navbar-link'  %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'Links', links_path, :class => 'navbar-link'  %></li>
      <div class="d-flex">
        <li>
          <%= link_to(edit_user_registration_path, class: 'navbar-link btn btn-secondary') do %>
            <i class="bi bi-gear"></i> Edit Profile
          <% end %>
        </li>
        <li>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn navbar-link btn btn-primary mx-3' %>
        </li>
      </div>
    </div>
    <% else %>
    <div class="d-flex">
      <li><%= link_to 'Sign In', new_user_session_path, :class => 'navbar-link btn btn-primary mx-3'  %></li>
      <li><%= link_to 'Sign Up', new_user_registration_path, :class => 'navbar-link btn btn-secondary'  %></li>
    </div>
    <% end %> 
  </ul>
</nav>