config/routes.rb
Rails.application.routes.draw do
  get 'about/index', to: 'about#index', as: 'about'
  get 'home/index'
  devise_for :users
  resources :links do
    member do
      get "visit_counter_chart"
      get "visit_detail"
    end
  end
  get "l/:slug" => "links#redirect_original_url", as: :redirect_original_url
  post "l/:slug" => "links#private_link_authentication", as: :private_link_authentication
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "home#index"
end

app/models/link.rb
class Link < ApplicationRecord
    belongs_to :user
    has_many :visits, dependent: :destroy
    validates :slug, presence: true, uniqueness: true
    validates :name, presence: false
    validates :link_type, presence: true
    validates :expiration_date, presence: true , if: :is_temporary?
    validates :password, presence: true , if: :is_private?
    validates :url, presence: true ,format: { with: URI.regexp }
    has_secure_password validations: false

    enum link_type: { regular: 'regular', temporary: 'temporary', private: 'private', ephemeral: 'ephemeral' }, _prefix: true

    before_validation :generate_slug_and_unique_url, on: :create
    
  # Types of links:
  # - Links regulares
  # - Links temporales - tiene atributo expiration_date datetime
  # - Links privados - tiene atributo password string
  # - Links efímeros - tiene atributo accessed boolean

  def self.link_disable
    update(accessed: true)
  end  

  private
  def generate_slug_and_unique_url
    self.slug ||= SecureRandom.hex(3)
  end

  def is_temporary?
    link_type == 'temporary'
  end

  def is_private?
    link_type == 'private'
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]
  before_action :authorize_user!, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[redirect_original_url private_link_authentication]

  # GET /links 
  def index
  """
  Show all the links of the current user paginated
  """
    @links = current_user.links.paginate(page: params[:page], per_page: 5)
  end

  # GET /links/1
  def show
  """
  Show the details of a link (url, shortlink, link type, expiration date, password, and reports)
  """
    @link = Link.find(params[:id])
    @short = redirect_original_url_url(@link.slug) 
  end

  # GET /links/new
  def new
  """
  Show the form to create a new link
  """  
    @link = Link.new
  end

  # POST /links
  def create
  """
  Create a new link
  """
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "The link was successfully created." }
        # format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  def update
  """
  Update a link
  """
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "The link was successfully updated." }
        # format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  def destroy
  """
  Delete a link
  """
    @link.destroy!
    respond_to do |format|
      format.html { redirect_to links_url, notice: "The link was successfully deleted." }
    end
  end

# GET /links/:slug
def redirect_original_url
"""
Redirect to the original url of the link depending on the link type. 
If the link is private, it renders a html form to enter the password.
"""
  @link = Link.find_by(slug: params[:slug])
  if @link.present?
    case @link.link_type
    when 'private'
      #Renders a html form to enter the password
      render 'private_link_password_view'
    when 'temporary'
      redirect_temporary_link
    when 'ephemeral'
      redirect_ephemeral_link
    else
      redirect_regular_link
    end
  else
    flash[:alert] = 'The Link doesn´t exist'
    redirect_to root_path
  end
end

# POST /links/:slug
def private_link_authentication
"""
Redirect to the original url of the link if the password is correct.
"""
  @link = Link.find_by(slug: params[:slug])

  if @link.present? && @link.authenticate(params[:password])
    Visit.create_visit(@link, current_time, request.remote_ip)
    redirect_to @link.url, allow_other_host: true
  else
    flash[:alert] = 'Password is incorrect. Please enter the correct password'
    render 'private_link_password_view'
  end
end

# GET /links/:id/visits
def visit_detail
  """ 
  All the visits of a link are shown with the IP address and datetime of the visit.
  Also there is a search engine to filter by IP address and datetime range.
  """
    @link = Link.find(params[:id]) 
    @q = @link.visits.ransack(params[:q])
    @visits_paginated = @q.result.paginate(page: params[:page], per_page: 6)
end
  

def visit_counter_chart
  """ 
  The number of visits per day of a link is shown.
  """
  @link = Link.find(params[:id]) 
  if @link.visits.present?
    @visit_counter_per_day = @link.visits.by_day
    @visit_counter_per_day.reject! { |day, count| count.zero? }
  else
    @visit_counter_per_day = {}
  end
end

private

  def redirect_regular_link
  """
  Redirect to the original url of the link
  """
    Visit.create_visit(@link, current_time, request.remote_ip)
    redirect_to @link.url, allow_other_host: true
  end

  def redirect_temporary_link
  """
  Redirect to the original url of the link if the expiration date is greater than the current date
  """
    if @link.expiration_date > current_time.to_date
      Visit.create_visit(@link, current_time, request.remote_ip)
      redirect_to @link.url, allow_other_host: true
    else
      not_found
    end
  end

  def redirect_ephemeral_link
  """
  Redirect to the original url of the link if the link has not been accessed before
  """
    if !@link.accessed?
      Link.link_disable
      Visit.create_visit(@link, current_time, request.remote_ip)
      redirect_to @link.url, allow_other_host: true
    else
      forbidden
    end
  end

  def current_time
    DateTime.now.strftime("%Y-%m-%d %H:%M:%S")
  end 

  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end

  def authorize_user!
    unless current_user == @link.user
      forbidden
    end
  end

  # Only allow a list of trusted parameters through.
  def link_params
  """
  Permit the parameters of the link
  """
    params.require(:link).permit(:name, :url, :expiration_date, :link_type, :password, :link_type)
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>
      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= form.label :link_type %>
      <%= form.select :link_type, Link.link_types.keys, {}, {:class => 'form-control'} %>
  </div>

   <div class="form-group">
    <%= form.label :name do %>
      <%= "Name (optional)" %>
    <% end %>
    <%= form.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <div class="form-group" id="temporary" style="display:none">
    <%= form.label :expiration_date, style: "display: block" %>
    <%= form.date_field :expiration_date, :class => "form-control" %>
  </div>

  <div class="form-group" id="private" style="display:none">
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, :class => "form-control" %>
  </div>

  <div class="my-3">
      <%= form.submit link.persisted? ? "Update Link" : "Create Link", class: "btn btn-success" %>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function() {
        var linkType = document.getElementById("link_link_type");
        var linkPassword = document.getElementById("private");
        var linkExpirationDate = document.getElementById("temporary");    

        linkType.addEventListener("change", function() {
          var type = linkType.value;
          // console.log(type);
          if (type === "private") {
            linkPassword.style.display = "block";
            linkExpirationDate.style.display = "none";
          } else if (type === "temporary") {
            linkPassword.style.display = "none";
            linkExpirationDate.style.display = "block";
          } else {
            linkPassword.style.display = "none";
            linkExpirationDate.style.display = "none";
          }
        });     
    });
  </script>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">

  <% if link.name.present? %>
    <h3><%= link.name %></h3>
  <% end %>

  <p class="mt-4">
    <strong>Link type:</strong>
    <%= link.link_type %>
  </p>

  <p>
    <strong>Original url:</strong>
    <a href=""><%= link.url %></a>
  </p>
  <p>
    <strong>Shortened URL:</strong>
    <%= link_to redirect_original_url_url(link.slug) ,redirect_original_url_url(link.slug)%>
  </p>
  <%# If it's a temporary link, it will expire on link.expiration_date %>
  <% if link.link_type == "temporary" %>
    <p>
      <strong>Expiration date:</strong>
      <%= link.expiration_date %>
    </p>
  <% else %>
      <% if link.link_type == "ephemeral" %>
        <p>
          <strong>Accessed: </strong>
            <%= link.accessed %>
        </p>
    <% end %>
  <% end %>
  <p>
    <strong>Created:</strong>
    <%= link.created_at.to_time.in_time_zone('America/Argentina/Buenos_Aires').strftime("%H:%M:%S -- %Y-%m-%d") %>
  </p>
    <p>
    <strong>Last Update:</strong>
    <%= link.updated_at.to_time.in_time_zone('America/Argentina/Buenos_Aires').strftime("%H:%M:%S -- %Y-%m-%d") %>
  </p>
</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>
<div>
  <%= link_to "Show this link", @link %>
</div>

app/views/links/index.html.erb
<div class="w-100 container">
  <div>
      <h2>Links</h2>
      <%= link_to "New link", new_link_path, class: "btn btn-success my-2" %> 
  </div>
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th>Original URL</th>
        <th>Category</th>
        <th>Shortened URL</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><a href=""><%= link.url %></a></td>
          <td><%= link.link_type %></td>
          <td>
            <%= link_to redirect_original_url_url(link.slug) ,redirect_original_url_url(link.slug)%>
          </td>
          <td class="d-flex">
            <%# Show button %>
            <%= link_to(link, class: 'btn btn-primary mr-1') do %>
              <i class="bi bi-zoom-in"></i> Show
            <% end %>
            <%# Edit button %>
            <%= link_to(edit_link_path(link), class: 'btn btn-secondary mx-1') do %>
              <i class="bi bi-pen"></i> Edit
            <% end %>
            <%# Delete button %>
            <%= button_to link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= will_paginate @link, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div> 
</div>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render "form", link: @link %>

<br>

app/views/links/private_link_password_view.html.erb
<div class="container d-flex flex-column w-25 ">
<h5>To access to the link, please enter password </h5>
<%= form_tag(private_link_authentication_path(params[:slug]), method: :post, class: "mt-4") do %>
  <div class="form-group mb-3">
    <% if flash[:alert].present? %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
      </div>
   <% end %>
    <%= label_tag(:password, "Link password:") %>
    <%= password_field_tag(:password, nil, class: "form-control") %>
  </div>
  <%= submit_tag('Accept', class: 'btn btn-success') %>
<% end %>
</div>

app/views/links/show.html.erb
<div class="container w-50">
  <%= render @link %>
  <div class="d-flex mt-4">
   <%= link_to visit_counter_chart_link_path(@link), class: "btn btn-success" do %>
      Daily visits counter
    <% end %> 
    <%= link_to visit_detail_link_path(@link), class: "btn btn-primary text-light mx-2" do %>
      Daily visits detail
    <% end %>
    <%# Edit button %>
    <%= button_to edit_link_path(@link), method: :get, class: "btn btn-secondary" do %>
      <i class="bi bi-pen"></i> Edit
    <% end %>
    <%# Delete button %>
    <%= button_to @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mx-2" do %>
      <i class="bi bi-trash"></i>
    <% end %>
  </div>
</div>

app/views/links/visit_counter_chart.html.erb
<div class="container">
  <h1 class="mb-4">Daily visits report</h1>
  
  <table class="table table-striped">
    <thead>
      <tr class="table-primary">
        <th scope="col">Date</th>
        <th scope="col">Visits count (per day)</th>
      </tr>
    </thead>
    <tbody>
      <% @visit_counter_per_day.each do |day, count| %>
          <tr>
            <td><%= day %></td>
            <td><%= count %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/links/visit_detail.html.erb
<div class="container">
  <h1 class="mb-4">Link visits</h1>

  <%= search_form_for @q, url: visit_detail_link_path, html: { class: 'mb-4' } do |f| %>
    <div class="row g-3">
      <div class="col-md-4">
        <%= f.label :ip_address_cont, 'Filter by IP Address:', class: 'form-label' %>
        <%= f.search_field :ip_address_cont, class: 'form-control' %>
      </div>

      <div class="col-md-4">
        <%= f.label :access_date_gteq, 'Filter from date:', class: 'form-label' %>
        <%= f.datetime_local_field :access_date_gteq, class: 'form-control' %>
      </div>

      <div class="col-md-4">
        <%= f.label :access_date_lteq, 'Filter until date:', class: 'form-label' %>
        <%= f.datetime_local_field :access_date_lteq, class: 'form-control' %>
      </div>

      <div class="col-12">
        <%= f.submit 'Filter', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>

  <div class="table-responsive">
    <table class="table table-striped mt-4">
      <thead>
        <tr class="table-secondary">
          <th scope="col">Datetime</th>
          <th scope="col">IP Address</th>
          <!-- Add other columns as needed -->
        </tr>
      </thead>
      <tbody>
        <% if @visits_paginated.present? %>
          <% @visits_paginated.each do |visit| %>
            <tr>
              <td><%= visit.access_date.strftime("%Y-%m-%d -- %H:%M:%S ") %></td>
              <td><%= visit.ip_address %></td>
              <!-- Add other columns as needed -->
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="2">No results found</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="text-center">
    <%= will_paginate @visits_paginated, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>